itam/urls.py
from django.urls import path, re_path
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from . import views

app_name = 'itam'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('', login_required(views.IndexView.as_view()), name='index'),
    path('activity/', login_required(views.ActivityLogView.as_view()), name='activity'),
    path('notification/', login_required(views.NotificationView.as_view()), name='notification'),
    path('notification/mark-as-read/<int:pk>/', login_required(views.mark_as_read_notification), name='mark-as-read'),
    path('notification/mark-all-as-read/', login_required(views.mark_all_as_read_notification), name='mark-all-as-read'),
    path('notification/delete/<int:pk>/', login_required(views.delete_notification), name='delete-notification'),
    path('notification/delete-all-notification/', login_required(views.delete_all_notification), name='delete-all-notification'),
    path('profile/change-password/', login_required(views.change_password), name='change-password'),
    path('computer/', login_required(views.ComputerList.as_view()), name='computer-list'),
    path('sfp/', login_required(views.SfpList.as_view()), name='sfp-list'),
    path('network_device/', login_required(views.NetworkDeviceList.as_view()), name='network-device-list'),
    path('os/', login_required(views.OperatingSystemList.as_view()), name='os-list'),
    path('mo/', login_required(views.MicrosoftOfficeList.as_view()), name='mo-list'),
    path('other-software/', login_required(views.OtherSoftwareList.as_view()), name='other-list'),
    path('users/', login_required(views.UserList.as_view()), name='user-list'),
    path('users/<int:pk>/', login_required(views.UserDetails.as_view()), name='user-details'),
    path('location/', login_required(views.LocationList.as_view()), name='location-list'),
    path('location/<int:pk>/', login_required(views.LocationDetails.as_view()), name='location-details'),
    path('computer/<int:pk>/', login_required(views.ComputerDetails.as_view()), name='computer-details'),
    path('sfp/<int:pk>/', login_required(views.SfpDetails.as_view()), name='sfp-details'),
    path('network_device/<int:pk>/', login_required(views.NetworkDeviceDetails.as_view()), name='network-device-details'),
    path('os/<int:pk>/', login_required(views.OperatingSystemDetails.as_view()), name='os-details'),
    path('mo/<int:pk>/', login_required(views.MicrosoftOfficeDetails.as_view()), name='mo-details'),
    path('other-software/<int:pk>/', login_required(views.OtherSoftwareDetails.as_view()), name='other-details'),
    path('computer/add/', login_required(views.ComputerCreate.as_view()), name='add-computer'),
    path('computer/edit/<int:pk>/', login_required(views.ComputerUpdate.as_view()), name='edit-computer'),
    path('computer/delete/<int:pk>/', login_required(views.ComputerDelete.as_view()), name='delete-computer'),
    path('sfp/add/', login_required(views.SfpCreate.as_view()), name='add-sfp'),
    path('sfp/edit/<int:pk>/', login_required(views.SfpUpdate.as_view()), name='edit-sfp'),
    path('sfp/delete/<int:pk>/', login_required(views.SfpDelete.as_view()), name='delete-sfp'),
    path('network_device/add/', login_required(views.NetworkDeviceCreate.as_view()), name='add-network-device'),
    path('network_device/edit/<int:pk>/', login_required(views.NetworkDeviceUpdate.as_view()), name='edit-network-device'),
    path('network_device/delete/<int:pk>/', login_required(views.NetworkDeviceDelete.as_view()), name='delete-network-device'),
    path('os/add/', login_required(views.OperatingSystemCreate.as_view()), name='add-os'),
    path('os/edit/<int:pk>/', login_required(views.OperatingSystemUpdate.as_view()), name='edit-os'),
    path('os/delete/<int:pk>/', login_required(views.OperatingSystemDelete.as_view()), name='delete-os'),
    path('mo/add/', login_required(views.MicrosoftOfficeCreate.as_view()), name='add-mo'),
    path('mo/edit/<int:pk>/', login_required(views.MicrosoftOfficeUpdate.as_view()), name='edit-mo'),
    path('mo/delete/<int:pk>/', login_required(views.MicrosoftOfficeDelete.as_view()), name='delete-mo'),
    path('other-software/add/', login_required(views.OtherSoftwareCreate.as_view()), name='add-other'),
    path('other-software/edit/<int:pk>/', login_required(views.OtherSoftwareUpdate.as_view()), name='edit-other'),
    path('other-software/delete/<int:pk>/', login_required(views.OtherSoftwareDelete.as_view()), name='delete-other'),
    path('users/add/', login_required(views.UserCreate.as_view()), name='add-user'),
    path('users/edit/<int:pk>/', login_required(views.UserUpdate.as_view()), name='edit-user'),
    path('users/delete/<int:pk>/', login_required(views.UserDelete.as_view()), name='delete-user'),
    path('location/add/', login_required(views.LocationCreate.as_view()), name='add-location'),
    path('location/edit/<int:pk>/', login_required(views.LocationUpdate.as_view()), name='edit-location'),
    path('location/delete/<int:pk>/', login_required(views.LocationDelete.as_view()), name='delete-location'),
    path('track/deployed_assets/os/', login_required(views.OperatingSystemTrackDeployed.as_view()), name='os-track-d'),
    path('track/deployed_assets/other-software/', login_required(views.OtherSoftwareTrackDeployed.as_view()), name='other-track-d'),
    path('track/deployed_assets/mo/', login_required(views.MicrosoftOfficeTrackDeployed.as_view()), name='mo-track-d'),
    path('track/deployed_assets/computer/', login_required(views.ComputerTrackDeployed.as_view()), name='computer-track-d'),
    path('track/deployed_assets/sfp/', login_required(views.SfpTrackDeployed.as_view()), name='sfp-track-d'),
    path('track/deployed_assets/network_device/', login_required(views.NetworkDeviceTrackDeployed.as_view()), name='network-device-track-d'),
    path('track/deployed_assets/monitor/', login_required(views.MonitorTrackDeployed.as_view()), name='monitor-track-d'),
    path('track/deployed_assets/printer/', login_required(views.PrinterTrackDeployed.as_view()), name='printer-track-d'),
    path('track/deployed_assets/scanner/', login_required(views.ScannerTrackDeployed.as_view()), name='scanner-track-d'),
    path('track/expiring_assets/computer/', login_required(views.ComputerTrackExpiring.as_view()), name='computer-track-e'),
    path('track/expiring_assets/monitor/', login_required(views.MonitorTrackExpiring.as_view()), name='monitor-track-e'),
    path('track/expiring_assets/printer/', login_required(views.PrinterTrackExpiring.as_view()), name='printer-track-e'),
    path('track/expiring_assets/scanner/', login_required(views.ScannerTrackExpiring.as_view()), name='scanner-track-e'),
    path('track/expiring_assets/network_device/', login_required(views.NetworkDeviceTrackExpiring.as_view()), name='network-device-track-e'),
    path('track/expiring_assets/sfp/', login_required(views.SfpTrackExpiring.as_view()), name='sfp-track-e'),
    path('track/expiring_assets/other-software/', login_required(views.OtherSoftwareTrackExpiring.as_view()), name='other-track-e'),
    path('monitor/', login_required(views.MonitorList.as_view()), name='monitor-list'),
    path('monitor/<int:pk>/', login_required(views.MonitorDetails.as_view()), name='monitor-details'),
    path('monitor/add/', login_required(views.MonitorCreate.as_view()), name='add-monitor'),
    path('monitor/edit/<int:pk>/', login_required(views.MonitorUpdate.as_view()), name='edit-monitor'),
    path('monitor/delete/<int:pk>/', login_required(views.MonitorDelete.as_view()), name='delete-monitor'),
    path('printer/', login_required(views.PrinterList.as_view()), name='printer-list'),
    path('printer/<int:pk>/', login_required(views.PrinterDetails.as_view()), name='printer-details'),
    path('printer/add/', login_required(views.PrinterCreate.as_view()), name='add-printer'),
    path('printer/edit/<int:pk>/', login_required(views.PrinterUpdate.as_view()), name='edit-printer'),
    path('printer/delete/<int:pk>/', login_required(views.PrinterDelete.as_view()), name='delete-printer'),
    path('scanner/', login_required(views.ScannerList.as_view()), name='scanner-list'),
    path('scanner/<int:pk>/', login_required(views.ScannerDetails.as_view()), name='scanner-details'),
    path('scanner/add/', login_required(views.ScannerCreate.as_view()), name='add-scanner'),
    path('scanner/edit/<int:pk>/', login_required(views.ScannerUpdate.as_view()), name='edit-scanner'),
    path('scanner/delete/<int:pk>/', login_required(views.ScannerDelete.as_view()), name='delete-scanner'),
    path('computer/archived_assets/', login_required(views.ComputerArchiveList.as_view()), name='computer-archive'),
    path('computer/archive/<int:pk>/', login_required(views.archive_computer), name='archive-computer'),
    path('monitor/archived_assets/', login_required(views.MonitorArchiveList.as_view()), name='monitor-archive'),
    path('monitor/archive/<int:pk>/', login_required(views.archive_monitor), name='archive-monitor'),
    path('printer/archived_assets/', login_required(views.PrinterArchiveList.as_view()), name='printer-archive'),
    path('printer/archive/<int:pk>/', login_required(views.archive_printer), name='archive-printer'),
    path('scanner/archived_assets/', login_required(views.ScannerArchiveList.as_view()), name='scanner-archive'),
    path('scanner/archive/<int:pk>/', login_required(views.archive_scanner), name='archive-scanner'),
    path('sfp/archived_assets/', login_required(views.SfpArchiveList.as_view()), name='sfp-archive'),
    path('sfp/archive/<int:pk>/', login_required(views.archive_sfp), name='archive-sfp'),
    path('network_device/archived_assets/', login_required(views.NetworkDeviceArchiveList.as_view()), name='network-device-archive'),
    path('network_device/archive/<int:pk>/', login_required(views.archive_network_device), name='archive-network-device'),

nocswebsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import notifications.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('itam.urls', namespace='itam'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

itam/templates/form-template.html
{% for field in form %}
	<div class="container">
		{% if field.errors %}
		<span class="text-danger small">*{{ field.errors | striptags }}</span>
		{% endif %}
		<div class="form-group row">
			<label {% if field.field.required %} class="font-weight-bold col-form-label col-md-4" {% endif %} class="col-form-label col-md-4">
				{{ field.label_tag }}
			</label>
			<div  class="col-md-8">
				{{ field }} <small class="form-text text-muted">{{ field.help_text | striptags }}</small>
			</div>
		</div>
	</div>
{% endfor %}

itam/templates/hardware-filter.html
          <div class="row mb-3">
            <div class="col-md-5 flex">
              <div class="mr-auto">
                <form class="form-inline" onchange="this.form.submit()" methods="GET" action="">
                  Filter: &nbsp;
                  <select class="custom-select custom-select-sm mr-1" name="filterInput">
                    <option selected="{{ filter_value }}" disabled>{{ filter_value }}</option>
                    <option value="All">All</option>
                    <option value="Deployed">Deployed</option>
                    <option value="Undeployed">Undeployed</option>
                  </select>
                  <button type="submit" class="btn btn-sm btn-info ">Go</button>
                </form>
              </div>
            </div>
            <div class="col-md-7 d-flex">
              <div class="ml-auto"> 
                <form class="form-inline" onchange="this.form.submit();" method="GET" action="" autocomplete="off">
                  Search: &nbsp;
                  <input name="searchInput" type="text" class="form-control form-control-sm mr-1">
                  <button type="submit" class="btn btn-sm btn-info ">Go</button>
                </form>
              </div>
            </div>
          </div>

itam/templates/pagination.html
{% load url_replace %}  
          <div class="row mt-3 mb-2">
            <div class="col-md-5">
              <form action="" method="GET" class="form-inline">
                Showing &nbsp; 
                <select class="custom-select" name="paginate_by" onchange="this.form.submit()">
                  <option selected="{{ paginate_value }}" disabled>{{ paginate_value }}</option>
                  <option value="10">10</option>
                  <option value="20">20</option>
                  <option value="30">30</option>
                  <option value="50">50</option>
                  <option value="100">100</option>
                </select>
                &nbsp;  rows per page
              </form>
            </div>
            {% if is_paginated %}
            <div class="col-md-7">
              <div class="float-right">
                  <nav aria-label="Page navigation example">
                    <ul class="pagination mb-0">
                      {% if page_obj.has_previous %}
                        <li class="page-item"><a class="page-link" href="?{% url_replace page=page_obj.previous_page_number %}">Previous</a></li>
                        </li>
                      {% else %}
                        <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
                      {% endif %}

                      {% if page_obj.number|add:'-1' > 1 %}
                        {% if page_obj.number != 1 %}
                          <li class="page-item"><a class="page-link" href="?{% url_replace page=1 %}">1</a>
                        {% endif %}
                        <li class="page-item disabled"><a class="page-link">&hellip;</a></li>
                      {% endif %}

                      {% for i in page_obj.paginator.page_range %}
                        {% if page_obj.number == i %}
                          <li class="page-item active"><a class="page-link" href="#">{{ i }}</a></li>
                        {% elif i > page_obj.number|add:'-2' and i < page_obj.number|add:'2' %}
                          <li class="page-item"><a class="page-link" href="?{% url_replace page=i %}">{{ i }}</a></li>
                        {% endif %}
                      {% endfor %}

                      {% if page_obj.paginator.num_pages > page_obj.number|add:'1' %}
                        <li class="page-item disabled"><a class="page-link">&hellip;</a></li>
                        {% if page_obj.number != page_obj.paginator.num_pages %}
                          <li class="page-item">
                            <a class="page-link" href="?{% url_replace page=page_obj.paginator.num_pages %}">
                              {{ page_obj.paginator.num_pages }}
                            </a>
                          </li>
                        {% endif %}
                      {% endif %}

                      {% if page_obj.has_next %}
                        <li class="page-item"><a class="page-link" href="?{% url_replace page=page_obj.next_page_number %}">Next</a></li>
                      {% else %}
                        <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
                      {% endif %}
                    </ul>
                  </nav>
              </div>
            </div>
            {% endif %}
          </div>

itam/templates/software-filter.html
          <div class="row mb-3">
            <div class="col-md-5 flex">
              <div class="mr-auto">
                <form class="form-inline" onchange="this.form.submit()" methods="GET" action="">
                  Filter: &nbsp;
                  <select class="custom-select custom-select-sm mr-1" name="filterInput">
                    <option selected="{{ filter_value }}" disabled>{{ filter_value }}</option>
                    <option value="All">All</option>
                    <option value="Installed">Installed</option>
                    <option value="Not Installed">Not Installed</option>
                  </select>
                  <button type="submit" class="btn btn-sm btn-info ">Go</button>
                </form>
              </div>
            </div>
            <div class="col-md-7 d-flex">
              <div class="ml-auto"> 
                <form class="form-inline" onchange="this.form.submit();" method="GET" action="" autocomplete="off">
                  Search: &nbsp;
                  <input name="searchInput" type="text" class="form-control form-control-sm mr-1">
                  <button type="submit" class="btn btn-sm btn-info ">Go</button>
                </form>
              </div>
            </div>
          </div>

itam/templates/tracking-navbar-e.html
    <ul class="nav nav-tabs card-header-tabs">
      <li class="nav-item">
        <a {% if active_page == 'computer_track_e' %} class="nav-link active" {% endif %} 
        class="nav-link" href="{% url 'itam:computer-track-e' %}">Computer
        </a>
      </li>
      <li class="nav-item">
        <a {% if active_page == 'monitor_track_e' %} class="nav-link active" {% endif %} 
        class="nav-link" href="{% url 'itam:monitor-track-e' %}">Monitor
        </a>
      </li>
      <li class="nav-item">
        <a {% if active_page == 'printer_track_e' %} class="nav-link active" {% endif %} 
        class="nav-link" href="{% url 'itam:printer-track-e' %}">Printer
        </a>
      </li>
      <li class="nav-item">
        <a {% if active_page == 'scanner_track_e' %} class="nav-link active" {% endif %} 
        class="nav-link" href="{% url 'itam:scanner-track-e' %}">Scanner
        </a>
      </li>
      <li class="nav-item">
        <a {% if active_page == 'network_device_track_e' %} class="nav-link active" {% endif %} 
        class="nav-link" href="{% url 'itam:network-device-track-e' %}">Network Device</a>
      </li>
      <li class="nav-item">
        <a {% if active_page == 'sfp_track_e' %} class="nav-link active" {% endif %} 
        class="nav-link" href="{% url 'itam:sfp-track-e' %}">Sfp</a>
      </li>
      <li class="nav-item">
        <a {% if active_page == 'others_track_e' %} class="nav-link active" {% endif %} 
        class="nav-link" href="{% url 'itam:other-track-e' %}">Other Software</a>
      </li>
    </ul> 

itam/templates/tracking-navbar.html
    <ul class="nav nav-tabs card-header-tabs">
      <li class="nav-item">
        <a {% if active_page == 'computer_track_d' %} class="nav-link active" {% endif %} 
        class="nav-link" href="{% url 'itam:computer-track-d' %}">Computer
        </a>
      </li>
      <li class="nav-item">
        <a {% if active_page == 'monitor_track_d' %} class="nav-link active" {% endif %} 
        class="nav-link" href="{% url 'itam:monitor-track-d' %}">Monitor
        </a>
      </li>
      <li class="nav-item">
        <a {% if active_page == 'printer_track_d' %} class="nav-link active" {% endif %} 
        class="nav-link" href="{% url 'itam:printer-track-d' %}">Printer
        </a>
      </li>
      <li class="nav-item">
        <a {% if active_page == 'scanner_track_d' %} class="nav-link active" {% endif %} 
        class="nav-link" href="{% url 'itam:scanner-track-d' %}">Scanner
        </a>
      </li>
      <li class="nav-item">
        <a {% if active_page == 'network_device_track_d' %} class="nav-link active" {% endif %} 
        class="nav-link" href="{% url 'itam:network-device-track-d' %}">Network Device</a>
      </li>
      <li class="nav-item">
        <a {% if active_page == 'sfp_track_d' %} class="nav-link active" {% endif %} 
        class="nav-link" href="{% url 'itam:sfp-track-d' %}">Sfp</a>
      </li>
      <li class="nav-item">
        <a {% if active_page == 'os_track_d' %} class="nav-link active" {% endif %} 
        class="nav-link" href="{% url 'itam:os-track-d' %}">Operating System</a>
      </li>
      <li class="nav-item">
        <a {% if active_page == 'mo_track_d' %} class="nav-link active" {% endif %} 
        class="nav-link" href="{% url 'itam:mo-track-d' %}">Microsoft Office</a>
      </li>
      <li class="nav-item">
        <a {% if active_page == 'others_track_d' %} class="nav-link active" {% endif %} 
        class="nav-link" href="{% url 'itam:other-track-d' %}">Other Software</a>
      </li>
    </ul> 