itam/urls.py
from django.urls import path, re_path
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from . import views

app_name = 'itam'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('', login_required(views.IndexView.as_view()), name='index'),
    path('activity/', login_required(views.ActivityLogView.as_view()), name='activity'),
    path('notification/', login_required(views.NotificationView.as_view()), name='notification'),
    path('notification/mark-as-read/<int:pk>/', login_required(views.mark_as_read_notification), name='mark-as-read'),
    path('notification/mark-all-as-read/', login_required(views.mark_all_as_read_notification), name='mark-all-as-read'),
    path('notification/delete/<int:pk>/', login_required(views.delete_notification), name='delete-notification'),
    path('notification/delete-all-notification/', login_required(views.delete_all_notification), name='delete-all-notification'),
    path('profile/change-password/', login_required(views.change_password), name='change-password'),
    path('computer/', login_required(views.ComputerList.as_view()), name='computer-list'),
    path('sfp/', login_required(views.SfpList.as_view()), name='sfp-list'),
    path('network_device/', login_required(views.NetworkDeviceList.as_view()), name='network-device-list'),
    path('os/', login_required(views.OperatingSystemList.as_view()), name='os-list'),
    path('mo/', login_required(views.MicrosoftOfficeList.as_view()), name='mo-list'),
    path('other-software/', login_required(views.OtherSoftwareList.as_view()), name='other-list'),
    path('users/', login_required(views.UserList.as_view()), name='user-list'),
    path('users/<int:pk>/', login_required(views.UserDetails.as_view()), name='user-details'),
    path('location/', login_required(views.LocationList.as_view()), name='location-list'),
    path('location/<int:pk>/', login_required(views.LocationDetails.as_view()), name='location-details'),
    path('computer/<int:pk>/', login_required(views.ComputerDetails.as_view()), name='computer-details'),
    path('sfp/<int:pk>/', login_required(views.SfpDetails.as_view()), name='sfp-details'),
    path('network_device/<int:pk>/', login_required(views.NetworkDeviceDetails.as_view()), name='network-device-details'),
    path('os/<int:pk>/', login_required(views.OperatingSystemDetails.as_view()), name='os-details'),
    path('mo/<int:pk>/', login_required(views.MicrosoftOfficeDetails.as_view()), name='mo-details'),
    path('other-software/<int:pk>/', login_required(views.OtherSoftwareDetails.as_view()), name='other-details'),
    path('computer/add/', login_required(views.ComputerCreate.as_view()), name='add-computer'),
    path('computer/edit/<int:pk>/', login_required(views.ComputerUpdate.as_view()), name='edit-computer'),
    path('computer/delete/<int:pk>/', login_required(views.ComputerDelete.as_view()), name='delete-computer'),
    path('sfp/add/', login_required(views.SfpCreate.as_view()), name='add-sfp'),
    path('sfp/edit/<int:pk>/', login_required(views.SfpUpdate.as_view()), name='edit-sfp'),
    path('sfp/delete/<int:pk>/', login_required(views.SfpDelete.as_view()), name='delete-sfp'),
    path('network_device/add/', login_required(views.NetworkDeviceCreate.as_view()), name='add-network-device'),
    path('network_device/edit/<int:pk>/', login_required(views.NetworkDeviceUpdate.as_view()), name='edit-network-device'),
    path('network_device/delete/<int:pk>/', login_required(views.NetworkDeviceDelete.as_view()), name='delete-network-device'),
    path('os/add/', login_required(views.OperatingSystemCreate.as_view()), name='add-os'),
    path('os/edit/<int:pk>/', login_required(views.OperatingSystemUpdate.as_view()), name='edit-os'),
    path('os/delete/<int:pk>/', login_required(views.OperatingSystemDelete.as_view()), name='delete-os'),
    path('mo/add/', login_required(views.MicrosoftOfficeCreate.as_view()), name='add-mo'),
    path('mo/edit/<int:pk>/', login_required(views.MicrosoftOfficeUpdate.as_view()), name='edit-mo'),
    path('mo/delete/<int:pk>/', login_required(views.MicrosoftOfficeDelete.as_view()), name='delete-mo'),
    path('other-software/add/', login_required(views.OtherSoftwareCreate.as_view()), name='add-other'),
    path('other-software/edit/<int:pk>/', login_required(views.OtherSoftwareUpdate.as_view()), name='edit-other'),
    path('other-software/delete/<int:pk>/', login_required(views.OtherSoftwareDelete.as_view()), name='delete-other'),
    path('users/add/', login_required(views.UserCreate.as_view()), name='add-user'),
    path('users/edit/<int:pk>/', login_required(views.UserUpdate.as_view()), name='edit-user'),
    path('users/delete/<int:pk>/', login_required(views.UserDelete.as_view()), name='delete-user'),
    path('location/add/', login_required(views.LocationCreate.as_view()), name='add-location'),
    path('location/edit/<int:pk>/', login_required(views.LocationUpdate.as_view()), name='edit-location'),
    path('location/delete/<int:pk>/', login_required(views.LocationDelete.as_view()), name='delete-location'),
    path('track/deployed_assets/os/', login_required(views.OperatingSystemTrackDeployed.as_view()), name='os-track-d'),
    path('track/deployed_assets/other-software/', login_required(views.OtherSoftwareTrackDeployed.as_view()), name='other-track-d'),
    path('track/deployed_assets/mo/', login_required(views.MicrosoftOfficeTrackDeployed.as_view()), name='mo-track-d'),
    path('track/deployed_assets/computer/', login_required(views.ComputerTrackDeployed.as_view()), name='computer-track-d'),
    path('track/deployed_assets/sfp/', login_required(views.SfpTrackDeployed.as_view()), name='sfp-track-d'),
    path('track/deployed_assets/network_device/', login_required(views.NetworkDeviceTrackDeployed.as_view()), name='network-device-track-d'),
    path('track/deployed_assets/monitor/', login_required(views.MonitorTrackDeployed.as_view()), name='monitor-track-d'),
    path('track/deployed_assets/printer/', login_required(views.PrinterTrackDeployed.as_view()), name='printer-track-d'),
    path('track/deployed_assets/scanner/', login_required(views.ScannerTrackDeployed.as_view()), name='scanner-track-d'),
    path('track/expiring_assets/computer/', login_required(views.ComputerTrackExpiring.as_view()), name='computer-track-e'),
    path('track/expiring_assets/monitor/', login_required(views.MonitorTrackExpiring.as_view()), name='monitor-track-e'),
    path('track/expiring_assets/printer/', login_required(views.PrinterTrackExpiring.as_view()), name='printer-track-e'),
    path('track/expiring_assets/scanner/', login_required(views.ScannerTrackExpiring.as_view()), name='scanner-track-e'),
    path('track/expiring_assets/network_device/', login_required(views.NetworkDeviceTrackExpiring.as_view()), name='network-device-track-e'),
    path('track/expiring_assets/sfp/', login_required(views.SfpTrackExpiring.as_view()), name='sfp-track-e'),
    path('track/expiring_assets/other-software/', login_required(views.OtherSoftwareTrackExpiring.as_view()), name='other-track-e'),
    path('monitor/', login_required(views.MonitorList.as_view()), name='monitor-list'),
    path('monitor/<int:pk>/', login_required(views.MonitorDetails.as_view()), name='monitor-details'),
    path('monitor/add/', login_required(views.MonitorCreate.as_view()), name='add-monitor'),
    path('monitor/edit/<int:pk>/', login_required(views.MonitorUpdate.as_view()), name='edit-monitor'),
    path('monitor/delete/<int:pk>/', login_required(views.MonitorDelete.as_view()), name='delete-monitor'),
    path('printer/', login_required(views.PrinterList.as_view()), name='printer-list'),
    path('printer/<int:pk>/', login_required(views.PrinterDetails.as_view()), name='printer-details'),
    path('printer/add/', login_required(views.PrinterCreate.as_view()), name='add-printer'),
    path('printer/edit/<int:pk>/', login_required(views.PrinterUpdate.as_view()), name='edit-printer'),
    path('printer/delete/<int:pk>/', login_required(views.PrinterDelete.as_view()), name='delete-printer'),
    path('scanner/', login_required(views.ScannerList.as_view()), name='scanner-list'),
    path('scanner/<int:pk>/', login_required(views.ScannerDetails.as_view()), name='scanner-details'),
    path('scanner/add/', login_required(views.ScannerCreate.as_view()), name='add-scanner'),
    path('scanner/edit/<int:pk>/', login_required(views.ScannerUpdate.as_view()), name='edit-scanner'),
    path('scanner/delete/<int:pk>/', login_required(views.ScannerDelete.as_view()), name='delete-scanner'),
    path('computer/archived_assets/', login_required(views.ComputerArchiveList.as_view()), name='computer-archive'),
    path('computer/archive/<int:pk>/', login_required(views.archive_computer), name='archive-computer'),
    path('monitor/archived_assets/', login_required(views.MonitorArchiveList.as_view()), name='monitor-archive'),
    path('monitor/archive/<int:pk>/', login_required(views.archive_monitor), name='archive-monitor'),
    path('printer/archived_assets/', login_required(views.PrinterArchiveList.as_view()), name='printer-archive'),
    path('printer/archive/<int:pk>/', login_required(views.archive_printer), name='archive-printer'),
    path('scanner/archived_assets/', login_required(views.ScannerArchiveList.as_view()), name='scanner-archive'),
    path('scanner/archive/<int:pk>/', login_required(views.archive_scanner), name='archive-scanner'),
    path('sfp/archived_assets/', login_required(views.SfpArchiveList.as_view()), name='sfp-archive'),
    path('sfp/archive/<int:pk>/', login_required(views.archive_sfp), name='archive-sfp'),
    path('network_device/archived_assets/', login_required(views.NetworkDeviceArchiveList.as_view()), name='network-device-archive'),
    path('network_device/archive/<int:pk>/', login_required(views.archive_network_device), name='archive-network-device'),

nocswebsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import notifications.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('itam.urls', namespace='itam'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

itam/templates/itam/hardware/monitor/display-monitors.html
{% extends 'base.html' %}
{% block title %} Monitors {% endblock %}
{% block content %}
<!-- SIDE BAR SECTION -->
    <!-- MAIN SECTION -->
	  <main class="main">
		  <div class="row">
        <div class="col-md-10">
          <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
              <li class="breadcrumb-item active">Hardware Assets</span></li>
              <li class="breadcrumb-item"><a href="{% url 'itam:monitor-list' %}"><span>Monitors</span></a></li>
            </ol>
          </nav>
        </div>
        <div class="col-md-2 mt-2 text-center">
          <div class="d-inline"><a class="btn btn-secondary" href="{% url 'itam:monitor-archive' %}">See Archive</a></div>
        </div>
      </div>

      {% if messages %}
      {% for message in messages %}
      <div class="alert alert-success alert-dismissible fade show">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      {% endfor %}
      {% endif %}      
      
		 <div class="card mb-3">
        <div class="card-header d-flex">
          <span class="mt-1">
            <i class="fas fa-list mr-2"></i> 
            All Monitor Assets
          </span>
          <div class="d-inline ml-auto"><a class="btn btn-sm btn-dark" href="{% url 'itam:add-monitor' %}"> Create New</a></div>
        </div>

        <div class="card-body">
          {% include 'hardware-filter.html' %}

          {% include 'pagination.html' %}
         
          <div class="row">
            <div class="col-md-12">
              <div class="table-responsive" style="overflow-x:auto;">
              <table class="table table-striped table-bordered tablesorter text-center" id="myTable" width="100%" cellspacing="0">
                <caption class='text-right'> 
                  <span class="mr-2 font-weight-bold">QR CODE</span><button class="mr-4 btn btn-sm btn-primary" disabled>
                    <i class="fas fa-qrcode"></i>
                  </button>
                  <span class="mr-2 font-weight-bold">EDIT</span><button class="mr-4 btn btn-sm btn-warning" disabled>
                    <i class="fa fa-pencil-alt" style="color: white"></i>
                  </button>
                  {% if request.user.is_admin %}
                  <span class="mr-2 font-weight-bold">ARCHIVE</span><button class="mr-4 btn btn-sm btn-secondary" disabled>
                    <i class="fas fas fa-archive"></i>
                  </button>
                  <span class="mr-2 font-weight-bold">DELETE</span><button class="mr-4 btn btn-sm btn-danger" disabled>
                    <i class="fa fa-trash-alt"></i>
                  </button>
                  {% endif %}
                </caption>
              <thead class="">
                <tr>
                  <th>Model</th>
                  <th>Brand</th>
                  <th>Deployment Status</th>
                  <th>Computer</th>
                  <th>Termination Date</th>
                  <th class="text-center">Termination Status</th>
                  <th class="text-center" style="min-width: 160px">Actions</th>
                </tr>
              </thead>
              <tbody id="myTbody">
                {% for m in monitors %}
                <tr>
                  <td><a href="{% url 'itam:monitor-details' m.id %}">{{ m.model }}</a></td>
                  <td>{{ m.brand }}</td>
                  <td>
                    <i class="fas fa-circle {% if m.deployment_status == 'Undeployed' %} text-warning {% else %} text-primary {% endif %}"></i> {{ m.deployment_status }}
                  </td>
                  <td>
                    {% if m.computer %}
                    <a href="{% url 'itam:computer-details' m.computer.id %}">{{ m.computer.computer_id }}</a>
                    {% endif %}
                  </td>
                  <td>{{ m.termination_date }}</td>
                  {% if m.termination_status %} 
                  <td class="text-center"><i class="fas fa-circle text-danger"></i></td> 
                  {% else %}
                  <td class="text-center"><i class="fas fa-circle text-success"></i></td>  
                  {% endif %}
                  <td class="text-center">
                    <form action="{% url 'itam:generate-monitor-qr' m.id %}" method="POST" style="display: inline">
                      {% csrf_token %}
                      <input type="hidden" name="m.id" value="{{ m.id }}"> 
                      <button type="submit" class="btn btn-sm btn-primary" title="Generate QR Code">
                        <i class="fas fa-qrcode"></i>
                      </button>
                    </form>

                    <a href="{% url 'itam:edit-monitor' m.id %}" class="btn btn-warning btn-sm" title="Edit">
                      <i class="fa fa-pencil-alt" style="color: white"></i>
                    </a>

                    {% if request.user.is_admin %}
                    <form action="{% url 'itam:archive-monitor' m.id %}" method="POST" style="display: inline">
                      {% csrf_token %}
                      <input type="hidden" name="monitor.id" value="{{ m.id }}"> 
                      <button type="submit" class="btn btn-sm btn-secondary" title="Archive"
                      onclick="return confirm('Are you sure you want to archive this Monitor?')">
                        <i class="fas fa-archive"></i>
                      </button>
                    </form>
                    {% endif %}
                      
                    {% if request.user.is_admin %}
                    <form action="{% url 'itam:delete-monitor' m.id %}" method="POST" style="display: inline">
                      {% csrf_token %}
                      <input type="hidden" name="monitor.id" value="{{ m.id }}"> 
                      <button type="submit" class="btn btn-sm btn-danger" title="Delete"
                      onclick="return confirm('Are you sure you want to delete this Monitor?')">
                        <i class="fa fa-trash-alt"></i>
                      </button>
                    </form>
                    {% endif %}
                  </td>
                </tr>
                {% endfor %}
                </tbody>
              </table>
              </div>
            </div>
          </div>
          {% include 'pagination.html' %}
        </div>
        <div class="card-footer">
         
        </div>
      </div>
		</main>
{% endblock %}

itam/templates/itam/hardware/monitor/monitor-archive.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %} Monitors {% endblock %}
{% block content %}
<!-- SIDE BAR SECTION -->
    <!-- MAIN SECTION -->
    <main class="main">
      <div class="row">
        <div class="col-md-10">
          <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
              <li class="breadcrumb-item active">Hardware Assets</span></li>
              <li class="breadcrumb-item"><a href="{% url 'itam:monitor-list' %}"><span>Monitors</span></a></li>
              <li class="breadcrumb-item"><a href="{% url 'itam:monitor-archive' %}"><span>Archive</span></a></li>
            </ol>
          </nav>
        </div>
        <div class="col-md-2 mt-2 text-center">
          <div class="d-inline"><a class="btn btn-secondary" href="{% url 'itam:monitor-list' %}">Back</a></div>
        </div>
      </div>

      {% if messages %}
      {% for message in messages %}
      <div class="alert alert-success alert-dismissible fade show">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      {% endfor %}
      {% endif %}

     <div class="card mb-3">
        <div class="card-header d-flex">
          <span class="mt-1">
            <i class="fas fa-list mr-2"></i> 
            All Archived Monitor Assets
          </span>
          <div class="d-inline ml-auto"><a class="btn btn-sm btn-dark" href="{% url 'itam:add-monitor' %}"> Create New</a></div>
        </div>
        <div class="card-body">
          {% include 'hardware-filter.html' %}
          
          {% include 'pagination.html' %}
         
          <div class="row">
            <div class="col-md-12">
              <div class="table-responsive" style="overflow-x:auto;">
              <table class="table table-striped table-bordered tablesorter text-center" id="myTable" width="100%" cellspacing="0">
                <caption class='text-right'> 
                  <span class="mr-2 font-weight-bold">UNARCHIVE</span><button class="mr-4 btn btn-sm btn-secondary" disabled>
                    <i class="fas fas fa-undo-alt"></i>
                  </button>
                  <span class="mr-2 font-weight-bold">QR CODE</span><button class="mr-4 btn btn-sm btn-primary" disabled>
                    <i class="fas fa-qrcode"></i>
                  </button>
                  <span class="mr-2 font-weight-bold">EDIT</span><button class="mr-4 btn btn-sm btn-warning" disabled>
                    <i class="fa fa-pencil-alt" style="color: white"></i>
                  </button>
                  {% if request.user.is_admin %}
                  <span class="mr-2 font-weight-bold">DELETE</span><button class="mr-4 btn btn-sm btn-danger" disabled>
                    <i class="fa fa-trash-alt"></i>
                  </button>
                  {% endif %}
                </caption>
              <thead class="">
                <tr>
                  <th>Model</th>
                  <th>Brand</th>
                  <th>Deployment Status</th>
                  <th>Computer</th>
                  <th>Termination Date</th>
                  <th class="text-center">Termination Status</th>
                  <th class="text-center">Actions</th>
                </tr>
              </thead>
              <tbody id="myTbody">
                {% for m in monitors %}
                <tr>
                  <td><a href="{% url 'itam:monitor-details' m.id %}">{{ m.model }}</a>
                    {% if m.is_archived %}
                    <span class="badge badge-pill badge-dark">ARCHIVED <i class="fas fa-times text-danger"></i></span>
                    {% endif %}
                  </td>
                  <td>{{ m.brand }}</td>
                  <td>
                    <i class="fas fa-circle {% if m.deployment_status == 'Undeployed' %} text-warning {% else %} text-primary {% endif %}"></i> {{ m.deployment_status }}
                  </td>
                  <td>
                    {% if m.computer %}
                    <a href="{% url 'itam:computer-details' m.computer.id %}">{{ m.computer.computer_id }}</a>
                    {% endif %}
                  </td>
                  <td>{{ m.termination_date }}</td>
                  {% if m.termination_status %} 
                  <td class="text-center"><i class="fas fa-circle text-danger"></i></td> 
                  {% else %}
                  <td class="text-center"><i class="fas fa-circle text-success"></i></td>  
                  {% endif %}
                  <td class="text-center">
                    {% if request.user.is_admin %}
                    <form action="{% url 'itam:unarchive-monitor' m.id %}" method="POST" style="display: inline">
                      {% csrf_token %}
                      <input type="hidden" name="monitor.id" value="{{ m.id }}"> 
                      <button type="submit" class="btn btn-sm btn-secondary" title="Unarchive"
                      onclick="return confirm('Are you sure you want to unarchive this Monitor?')">
                        <i class="fas fa-undo-alt"></i>
                      </button>
                    </form>
                    {% endif %}

                    <form action="{% url 'itam:generate-monitor-qr' m.id %}" method="POST" style="display: inline">
                      {% csrf_token %}
                      <input type="hidden" name="m.id" value="{{ m.id }}"> 
                      <button type="submit" class="btn btn-sm btn-primary" title="Generate QR Code">
                        <i class="fas fa-qrcode"></i>
                      </button>
                    </form>

                    <a href="{% url 'itam:edit-monitor' m.id %}" class="btn btn-warning btn-sm" title="Edit">
                      <i class="fa fa-pencil-alt" style="color: white"></i>
                    </a>
                      
                    {% if request.user.is_admin %}
                    <form action="{% url 'itam:delete-monitor' m.id %}" method="POST" style="display: inline">
                      {% csrf_token %}
                      <input type="hidden" name="monitor.id" value="{{ m.id }}"> 
                      <button type="submit" class="btn btn-sm btn-danger" title="Delete"
                      onclick="return confirm('Are you sure you want to delete this Monitor?')">
                        <i class="fa fa-trash-alt"></i>
                      </button>
                    </form>
                    {% endif %}
                  </td>
                </tr>
                {% endfor %}
                </tbody>
              </table>
              </div>
            </div>
          </div>

          {% include 'pagination.html' %}

        </div>
        
        <div class="card-footer">
        </div>

      </div>
    </main>
{% endblock %}

itam/templates/itam/hardware/monitor/monitor-details.html
{% extends 'base.html' %}
{% block title %} Monitor {% endblock %}
{% block content %}
<!-- SIDE BAR SECTION -->
    <!-- MAIN SECTION -->
	  <main class="main">
		  <div class="row">
        <div class="col-md-12">
          <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
              <li class="breadcrumb-item active">Hardware Assets</span></li>
              <li class="breadcrumb-item"><a href="{% url 'itam:monitor-list' %}"><span>Monitors</span></a></li>
              <li class="breadcrumb-item"><a href="{% url 'itam:monitor-details' object.id%}"><span>{{ object.model }}</span></a></li>
            </ol>
          </nav>
        </div>
      </div>

      {% if messages %}
      {% for message in messages %}
      <div class="alert alert-success alert-dismissible fade show">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      {% endfor %}
      {% endif %}
    
		 <div class="card mb-3">
        <div class="card-header d-flex">
          <span class="">
            <i class="fas fa-info mr-2 mt-2"></i>
            {{ object.model }} Details
          </span>
          <div class="dropdown ml-auto">
            <button class="btn btn-sm btn-dark dropdown-toggle" type="button" id="dropdownMenuButton" 
            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> Actions
            </button>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
              <a class="dropdown-item" href="{% url 'itam:edit-monitor' object.id %}">
                Edit
              </a>
              {% if request.user.is_admin %}
              <a class="dropdown-item">           
                <form action="{% url 'itam:delete-monitor' object.id %}" method="POST" style="display: inline">
                  {% csrf_token %}
                  <input type="hidden" name="monitor.id" value="{{ object.id }}"> 
                  <button type="submit" class="pl-0 dropdown-item" title="Delete" style="cursor: pointer;"
                  onclick="return confirm('Are you sure you want to delete this Monitor?')">
                    Delete
                  </button>
                </form> 
              </a>
              {% endif %}
              {% if request.user.is_admin and not object.is_archived %}
              <a class="dropdown-item">
                <form action="{% url 'itam:archive-monitor' object.id %}" method="POST" style="display: inline">
                  {% csrf_token %}
                  <input type="hidden" name="monitor.id" value="{{ object.id }}"> 
                  <button type="submit" class="pl-0 dropdown-item" title="Archive" style="cursor: pointer;"
                  onclick="return confirm('Are you sure you want to archive this Monitor?')">
                    Archive
                  </button>
                </form>
              </a>
              {% elif request.user.is_admin and object.is_archived %}
              <a class="dropdown-item">
                <form action="{% url 'itam:unarchive-monitor' object.id %}" method="POST" style="display: inline">
                  {% csrf_token %}
                  <input type="hidden" name="monitor.id" value="{{ object.id }}"> 
                  <button type="submit" class="pl-0 dropdown-item" title="Unarchive" style="cursor: pointer;"
                  onclick="return confirm('Are you sure you want to unarchive this Monitor?')">
                    Unarchive
                  </button>
                </form>
              </a>
              {% endif %}
              <a class="dropdown-item">
                <form action="{% url 'itam:generate-monitor-qr' object.id %}" method="POST" style="display: inline">
                  {% csrf_token %}
                  <input type="hidden" name="m.id" value="{{ object.id }}"> 
                  <button type="submit" class="pl-0 dropdown-item" title="Generate QR Code" style="cursor: pointer;">
                    Generate QR Code
                  </button>
                </form>
              </a>
            </div>
          </div>
        </div>

        <div class="card-body">
          <div class="row">
            <div class="col-md-12">
              <div class="table-responsive">
                <table class="table table-hover" width="100%">
                  <tbody>
                    <tr>
                      <td>Model</td>
                      <td>
                        {{ object.model }}
                        {% if object.is_archived %}
                        <span class="badge badge-pill badge-dark">ARCHIVED <i class="fas fa-times text-danger"></i></span> 
                        {% endif %}
                      </td>
                    </tr>
                    <tr>
                      <td>Brand</td>
                      <td>
                        {{ object.brand }}
                      </td>
                    </tr>
                    <tr>
                      <td>Serial Number</td>
                      <td>
                        {{ object.serial_number }}
                      </td>
                    </tr>
                    <tr>
                      <td>Computer</td>
                      <td>
                        {% if object.computer %}
                        <a href="{% url 'itam:computer-details' object.computer.id %}">{{ object.computer}}</a>
                        {% endif %}
                      </td>
                    </tr>
                    <tr>
                      <td>Deployment Date</td>
                      <td>
                        {{ object.deployment_date }}
                      </td>
                    </tr>
                    <tr>
                      <td>Deployment Status</td>
                      <td>
                        <i class="fas fa-circle {% if object.deployment_status == 'Undeployed' %} text-warning {% else %} text-primary {% endif %}"></i> {{ object.deployment_status }}
                      </td>
                    </tr>
                    <tr>
                      <td>Termination Date</td>
                      <td>
                        {{ object.termination_date }}
                      </td>
                    </tr>
                    <tr>
                      <td>Termination Status</td>
                      {% if object.termination_status %}
                      <td>
                       <i class="fas fa-circle text-danger"></i>
                      </td>
                      {% else %}
                      <td>
                       <i class="fas fa-circle text-success"></i>
                      </td>
                      {% endif %}
                    </tr>
                  </tbody>
                </table>  
              </div>
            </div>       
          </div>
        </div>
        <div class="card-footer">
          <div class="row mt-3">
           
          </div>
        </div>
      </div>
		</main>
{% endblock %}