itam/urls.py
from django.urls import path, re_path
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from . import views

app_name = 'itam'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('', login_required(views.IndexView.as_view()), name='index'),
    path('activity/', login_required(views.ActivityLogView.as_view()), name='activity'),
    path('notification/', login_required(views.NotificationView.as_view()), name='notification'),
    path('notification/mark-as-read/<int:pk>/', login_required(views.mark_as_read_notification), name='mark-as-read'),
    path('notification/mark-all-as-read/', login_required(views.mark_all_as_read_notification), name='mark-all-as-read'),
    path('notification/delete/<int:pk>/', login_required(views.delete_notification), name='delete-notification'),
    path('notification/delete-all-notification/', login_required(views.delete_all_notification), name='delete-all-notification'),
    path('profile/change-password/', login_required(views.change_password), name='change-password'),
    path('computer/', login_required(views.ComputerList.as_view()), name='computer-list'),
    path('sfp/', login_required(views.SfpList.as_view()), name='sfp-list'),
    path('network_device/', login_required(views.NetworkDeviceList.as_view()), name='network-device-list'),
    path('os/', login_required(views.OperatingSystemList.as_view()), name='os-list'),
    path('mo/', login_required(views.MicrosoftOfficeList.as_view()), name='mo-list'),
    path('other-software/', login_required(views.OtherSoftwareList.as_view()), name='other-list'),
    path('users/', login_required(views.UserList.as_view()), name='user-list'),
    path('users/<int:pk>/', login_required(views.UserDetails.as_view()), name='user-details'),
    path('location/', login_required(views.LocationList.as_view()), name='location-list'),
    path('location/<int:pk>/', login_required(views.LocationDetails.as_view()), name='location-details'),
    path('computer/<int:pk>/', login_required(views.ComputerDetails.as_view()), name='computer-details'),
    path('sfp/<int:pk>/', login_required(views.SfpDetails.as_view()), name='sfp-details'),
    path('network_device/<int:pk>/', login_required(views.NetworkDeviceDetails.as_view()), name='network-device-details'),
    path('os/<int:pk>/', login_required(views.OperatingSystemDetails.as_view()), name='os-details'),
    path('mo/<int:pk>/', login_required(views.MicrosoftOfficeDetails.as_view()), name='mo-details'),
    path('other-software/<int:pk>/', login_required(views.OtherSoftwareDetails.as_view()), name='other-details'),
    path('computer/add/', login_required(views.ComputerCreate.as_view()), name='add-computer'),
    path('computer/edit/<int:pk>/', login_required(views.ComputerUpdate.as_view()), name='edit-computer'),
    path('computer/delete/<int:pk>/', login_required(views.ComputerDelete.as_view()), name='delete-computer'),
    path('sfp/add/', login_required(views.SfpCreate.as_view()), name='add-sfp'),
    path('sfp/edit/<int:pk>/', login_required(views.SfpUpdate.as_view()), name='edit-sfp'),
    path('sfp/delete/<int:pk>/', login_required(views.SfpDelete.as_view()), name='delete-sfp'),
    path('network_device/add/', login_required(views.NetworkDeviceCreate.as_view()), name='add-network-device'),
    path('network_device/edit/<int:pk>/', login_required(views.NetworkDeviceUpdate.as_view()), name='edit-network-device'),
    path('network_device/delete/<int:pk>/', login_required(views.NetworkDeviceDelete.as_view()), name='delete-network-device'),
    path('os/add/', login_required(views.OperatingSystemCreate.as_view()), name='add-os'),
    path('os/edit/<int:pk>/', login_required(views.OperatingSystemUpdate.as_view()), name='edit-os'),
    path('os/delete/<int:pk>/', login_required(views.OperatingSystemDelete.as_view()), name='delete-os'),
    path('mo/add/', login_required(views.MicrosoftOfficeCreate.as_view()), name='add-mo'),
    path('mo/edit/<int:pk>/', login_required(views.MicrosoftOfficeUpdate.as_view()), name='edit-mo'),
    path('mo/delete/<int:pk>/', login_required(views.MicrosoftOfficeDelete.as_view()), name='delete-mo'),
    path('other-software/add/', login_required(views.OtherSoftwareCreate.as_view()), name='add-other'),
    path('other-software/edit/<int:pk>/', login_required(views.OtherSoftwareUpdate.as_view()), name='edit-other'),
    path('other-software/delete/<int:pk>/', login_required(views.OtherSoftwareDelete.as_view()), name='delete-other'),
    path('users/add/', login_required(views.UserCreate.as_view()), name='add-user'),
    path('users/edit/<int:pk>/', login_required(views.UserUpdate.as_view()), name='edit-user'),
    path('users/delete/<int:pk>/', login_required(views.UserDelete.as_view()), name='delete-user'),
    path('location/add/', login_required(views.LocationCreate.as_view()), name='add-location'),
    path('location/edit/<int:pk>/', login_required(views.LocationUpdate.as_view()), name='edit-location'),
    path('location/delete/<int:pk>/', login_required(views.LocationDelete.as_view()), name='delete-location'),
    path('track/deployed_assets/os/', login_required(views.OperatingSystemTrackDeployed.as_view()), name='os-track-d'),
    path('track/deployed_assets/other-software/', login_required(views.OtherSoftwareTrackDeployed.as_view()), name='other-track-d'),
    path('track/deployed_assets/mo/', login_required(views.MicrosoftOfficeTrackDeployed.as_view()), name='mo-track-d'),
    path('track/deployed_assets/computer/', login_required(views.ComputerTrackDeployed.as_view()), name='computer-track-d'),
    path('track/deployed_assets/sfp/', login_required(views.SfpTrackDeployed.as_view()), name='sfp-track-d'),
    path('track/deployed_assets/network_device/', login_required(views.NetworkDeviceTrackDeployed.as_view()), name='network-device-track-d'),
    path('track/deployed_assets/monitor/', login_required(views.MonitorTrackDeployed.as_view()), name='monitor-track-d'),
    path('track/deployed_assets/printer/', login_required(views.PrinterTrackDeployed.as_view()), name='printer-track-d'),
    path('track/deployed_assets/scanner/', login_required(views.ScannerTrackDeployed.as_view()), name='scanner-track-d'),
    path('track/expiring_assets/computer/', login_required(views.ComputerTrackExpiring.as_view()), name='computer-track-e'),
    path('track/expiring_assets/monitor/', login_required(views.MonitorTrackExpiring.as_view()), name='monitor-track-e'),
    path('track/expiring_assets/printer/', login_required(views.PrinterTrackExpiring.as_view()), name='printer-track-e'),
    path('track/expiring_assets/scanner/', login_required(views.ScannerTrackExpiring.as_view()), name='scanner-track-e'),
    path('track/expiring_assets/network_device/', login_required(views.NetworkDeviceTrackExpiring.as_view()), name='network-device-track-e'),
    path('track/expiring_assets/sfp/', login_required(views.SfpTrackExpiring.as_view()), name='sfp-track-e'),
    path('track/expiring_assets/other-software/', login_required(views.OtherSoftwareTrackExpiring.as_view()), name='other-track-e'),
    path('monitor/', login_required(views.MonitorList.as_view()), name='monitor-list'),
    path('monitor/<int:pk>/', login_required(views.MonitorDetails.as_view()), name='monitor-details'),
    path('monitor/add/', login_required(views.MonitorCreate.as_view()), name='add-monitor'),
    path('monitor/edit/<int:pk>/', login_required(views.MonitorUpdate.as_view()), name='edit-monitor'),
    path('monitor/delete/<int:pk>/', login_required(views.MonitorDelete.as_view()), name='delete-monitor'),
    path('printer/', login_required(views.PrinterList.as_view()), name='printer-list'),
    path('printer/<int:pk>/', login_required(views.PrinterDetails.as_view()), name='printer-details'),
    path('printer/add/', login_required(views.PrinterCreate.as_view()), name='add-printer'),
    path('printer/edit/<int:pk>/', login_required(views.PrinterUpdate.as_view()), name='edit-printer'),
    path('printer/delete/<int:pk>/', login_required(views.PrinterDelete.as_view()), name='delete-printer'),
    path('scanner/', login_required(views.ScannerList.as_view()), name='scanner-list'),
    path('scanner/<int:pk>/', login_required(views.ScannerDetails.as_view()), name='scanner-details'),
    path('scanner/add/', login_required(views.ScannerCreate.as_view()), name='add-scanner'),
    path('scanner/edit/<int:pk>/', login_required(views.ScannerUpdate.as_view()), name='edit-scanner'),
    path('scanner/delete/<int:pk>/', login_required(views.ScannerDelete.as_view()), name='delete-scanner'),
    path('computer/archived_assets/', login_required(views.ComputerArchiveList.as_view()), name='computer-archive'),
    path('computer/archive/<int:pk>/', login_required(views.archive_computer), name='archive-computer'),
    path('monitor/archived_assets/', login_required(views.MonitorArchiveList.as_view()), name='monitor-archive'),
    path('monitor/archive/<int:pk>/', login_required(views.archive_monitor), name='archive-monitor'),
    path('printer/archived_assets/', login_required(views.PrinterArchiveList.as_view()), name='printer-archive'),
    path('printer/archive/<int:pk>/', login_required(views.archive_printer), name='archive-printer'),
    path('scanner/archived_assets/', login_required(views.ScannerArchiveList.as_view()), name='scanner-archive'),
    path('scanner/archive/<int:pk>/', login_required(views.archive_scanner), name='archive-scanner'),
    path('sfp/archived_assets/', login_required(views.SfpArchiveList.as_view()), name='sfp-archive'),
    path('sfp/archive/<int:pk>/', login_required(views.archive_sfp), name='archive-sfp'),
    path('network_device/archived_assets/', login_required(views.NetworkDeviceArchiveList.as_view()), name='network-device-archive'),
    path('network_device/archive/<int:pk>/', login_required(views.archive_network_device), name='archive-network-device'),

nocswebsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import notifications.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('itam.urls', namespace='itam'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

itam/templates/itam/activity_log.html
{% extends 'base.html' %}
{% load activity_tags %}
{% block title %} Activity Logs {% endblock %}
{% block content %}
  <!-- MAIN SECTION -->
	<main class="main">

		<nav aria-label="breadcrumb">
			<ol class="breadcrumb">
        <li class="breadcrumb-item active"><span>Activity</span></li>
			</ol>
		</nav>

      <div class="card">
        <div class="card-header">
          <span class=""><i class="fas fa-clipboard-list mr-2"></i>Activity Log</span> 
        </div>
        <div class="card-body">
          <div class="row mb-3">
            <div class="col-md-5 flex">
              <div class="mr-auto">
                <form class="form-inline" onchange="this.form.submit()" methods="GET" action="">
                  Filter: &nbsp;
                  <select class="custom-select custom-select-sm mr-1" name="filterInput">
                    <option selected="{{ filter_value }}" disabled>{{ filter_value }}</option>
                    <option value="All">All</option>
                    <option value="created">Created</option>
                    <option value="updated">Updated</option>
                    <option value="archived">Archived</option>
                    <option value="unarchived">Unarchived</option>
                    <option value="deleted">Deleted</option>
                  </select>
                  <button type="submit" class="btn btn-sm btn-info ">Go</button>
                </form>
              </div>
            </div>
            <div class="col-md-7 d-flex">
 
            </div>
          </div>
          {% include 'pagination.html' %}

          <div class="table-responsive">
            <table class="table table-striped table-bordered tablesorter" id="myTable">
              <thead>
                <tr>
                  <th>Date</th>
                  <th>User</th>
                  <th>Action</th>
                  <th>Asset</th>
                <tr>
              </thead>
              <tbody id="myTbody">
                {% for action in actions %}
                <tr>
                  <td>{{ action.timestamp }}</td>
                  <td><a href="{{ action.actor.get_absolute_url }}">{{ action.actor }}</a></td>
                  <td>{{ action.verb }}</td>
                  {% if action.action_object %}
                  <td><a href="{{ action.action_object.get_absolute_url }}">{{ action.action_object }}</a></td>
                  {% else %}
                  <td>deleted...</td>
                  {% endif %}
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
          {% include 'pagination.html' %}
        </div>
      </div>


	</main>
{% endblock %}

itam/templates/itam/add-backup.html
{% extends 'base.html' %}
{% block title %} Users {% endblock %}
{% block content %}
<main class="main">
  <div class="row">
    <div class="col-md-12">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'itam:backup-list' %}"><span>Backup</span></a></li>
        <li class="breadcrumb-item active"><span>Import</span></li>
      </ol>
    </nav>
    </div>
  </div>

    <div style="width:800px;" class="container">
      <div class="card mt-3 custom-card">
        <div class="card-header">
          <div class="container"><i class="mt-1 far fa-plus-square"></i><span class="ml-2">Import</span></div>
        </div>
    
        <div class="card-body pb-2">
          <form action="" method="POST" enctype="multipart/form-data" autocomplete="off">
            {% csrf_token %}
            {% include 'form-template.html' %}
        </div>
        <div class="card-footer text-right pb-0">
          <div class="form-group row">
            <div class="col-sm-6">
            </div>
            <div class="col-sm-3">
              <a href="{% url 'itam:backup-list' %}" type="button" class="form-control btn btn-danger">Cancel</a>
            </div>
            <div class="col-sm-3">
              <button type="submit" class="form-control btn btn-success">Submit</button>
            </div>
          </div>
        </form>
        </div>
      </div>
</main>
{% endblock %}

itam/templates/itam/index.html
{% extends 'base.html' %}
{% load activity_tags %}
{% block title %} Dashboard {% endblock %}
{% block content %}
  <!-- MAIN SECTION -->
	<main class="main">

		<nav aria-label="breadcrumb">
			<ol class="breadcrumb">
				<li class="breadcrumb-item"><a href="{% url 'itam:index' %}"><span>Dashboard</span></a></li>
        <li class="breadcrumb-item active"><span>My Dashboard</span></li>
			</ol>
		</nav>

    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-success alert-dismissible fade show">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endfor %}
    {% endif %}

	 {% if request.user.is_admin %}
		<div class="row mb-3 text-center">

			<div class="col-md-3">
        <div class="card bg-primary text-white" style="border-radius: 0;">
          <div class="card-body pb-4">
            <div class="float-left text-left">
              <span><h4 class="font-weight-bold">{{ desktop_count }}</h4>HARDWARE</span>
            </div>
            <div class="float-right">
              <span><i class="fas fa-desktop" style="font-size: 50px;"></i></span>
            </div>
          </div>
          <div class="card-footer small" href="#">
      
          </div>
				</div>

      </div>

      <div class="col-md-3">
        <div class="card bg-warning text-white" style="border-radius: 0;">
          <div class="card-body pb-4">
            <div class="float-left text-left">
              <span><h4 class="font-weight-bold">{{ network_count }}</h4>NETWORK</span>
            </div>
            <div class="float-right">
              <span><i class="fas fa-server" style="font-size: 50px;"></i></span>
            </div>
          </div>
          <div class="card-footer text-muted small" href="#">
              
          </div>
        </div>
      </div>

			<div class="col-md-3">
        <div class="card bg-dark text-white" style="border-radius: 0;">
          <div class="card-body pb-4">
            <div class="float-left text-left">
              <span><h4 class="font-weight-bold">{{ software_count }}</h4>SOFTWARE</span>
            </div>
            <div class="float-right">
              <span><i class="fab fa-linux" style="font-size: 50px;"></i></span>
            </div>
          </div>
          <div class="card-footer small" href="#">
              
          </div>
        </div>
      </div>

      <div class="col-md-3">
        <div class="card bg-danger text-white" style="border-radius: 0;">
          <div class="card-body pb-4">
            <div class="float-left text-left">
              <span><h4 class="font-weight-bold">{{ user_count }}</h4>USERS</span>
            </div>
            <div class="float-right">
              <span><i class="fas fa-users" style="font-size: 50px;"></i></span>
            </div>
          </div>
          <div class="card-footer" href="{% url 'itam:user-list' %}">
          </div>
        </div>  
      </div>
		</div>
		<div class="card custom-card">
      <div class="card-header pr-4 pl-4">
		    <h5 class="float-left mt-1">Recent Activity</h5>
        <button class="btn btn-sm btn-outline-info float-right" data-target="#recentActivity" role="button" data-toggle="collapse" aria-expanded="true" aria-controls="recentActivity">
          <i class="fa fa-minus"></i>
          <i class="fa fa-plus"></i>
        </button>
      </div>

      <div class="collapse show" id="recentActivity">
      <div class="card-body">
        <div class="table-responsive">
          <ul class="list-group">
            {% activity_stream 'model' user %}
            {% for action in stream|slice:":5" %}
              <li href=# class="list-group-item list-group-item-action">{% display_action action %}</li>
            {% endfor %}
          </ul>
        </div>
      </div>

      <div class="card-footer small text-muted">
        <a class="btn btn-info w-100 text-white" href="{% url 'itam:activity' %}">View All</a>
      </div>

      </div>
    </div>
    {% endif %}

    <div class="row mt-3">
      <div class="col-md-6">
        <div class="card custom-card">
          <div class="card-header pr-4 pl-4">
            <h5 class="float-left mt-1"></i>Hardware Assets by Status</h5>
            <button class="btn btn-sm btn-outline-info float-right p-1 pr-2 pl-2" data-target="#hardwareCategoryCollapse" role="button" data-toggle="collapse" aria-expanded="false" aria-controls="hardwareCategoryCollapse">
              <i class="fa fa-minus small"></i>
              <i class="fa fa-plus small"></i>
            </button>
          </div>

        <div class="collapse" id="hardwareCategoryCollapse">
          <div class="card-body">
            <div class="table-responsive">
            <table class="table table-striped table-bordered text-center tablesorter" width="100%" cellspacing="0">
              <thead class="">
                <tr>
                  <th>Name</th>
                  <th>Quantity</th>
                </tr>
              </thead>
              <tbody>
                
              </tbody>
            </table>
            </div>
          </div>
          <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
        </div>
      </div>
      </div>
      <div class="col-md-6">
          <div class="card custom-card">
            <div class="card-header pr-4 pl-4">
              <h5 class="float-left mt-1"></i>Software Assets by Status</h5>
              <button class="btn btn-sm btn-outline-info float-right p-1 pr-2 pl-2" data-target="#softwareCategoryCollapse" role="button" data-toggle="collapse" aria-expanded="false" aria-controls="softwareCategoryCollapse">
                <i class="fa fa-minus small"></i>
                <i class="fa fa-plus small"></i>
              </button>
            </div>

            <div class="collapse" id="softwareCategoryCollapse">
            <div class="card-body">
              <div class="table-responsive">
                  <table class="table table-striped table-bordered text-center tablesorter" width="100%" cellspacing="0">
                     <thead class="">
                      <tr>
                        <th>Name</th>
                        <th>Quantity</th>
                      </tr>
                    </thead>
                    <tbody>
                     
                    </tbody>
                  </table>
              </div>
            </div>
            <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
          </div>
        </div>
            </div>
    </div>

	</main>
{% endblock %}

itam/templates/itam/login.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="https://my.adnu.edu.ph/assets/images/adnu_logo_white.png">

    <title>NOCS ITAM</title>
    {% load staticfiles %}
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/signin.css' %}" rel="stylesheet">
    <link href="{% static 'css/sticky-footer-navbar.css' %}" rel="stylesheet">
  </head>

  <body class="text-center">

    <header>
      <nav class="navbar navbar-expand-md navbar-dark fixed-top" style="background:#369; border-bottom: 2px solid rgb(255, 153, 51);">
        <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'itam:login' %}">
         <img class="mb-1 mr-2" src="{% static 'images/adnu_logo.png' %}" alt="" width="20" height="20"> NOCS ITAM
        </a>
      </div>
      </nav>
    </header>

   <main role="main" class="container">
    <form class="form-signin" method="POST">
      {% csrf_token %}
      <img class="mb-5 mt-0" src="{% static 'images/adnu_logo.png' %}" alt="" width="130" height="130">
      <h4 class="text-muted mt-0">Welcome to NOCS ITAM</h4>
      <hr class="mb-4">
      <div class="alert alert-warning text-center" role="alert"><span style="font-weight: 600;">Please Login</span></div>
      
      {% if messages %}
      {% for message in messages %}
      <div class="alert alert-success alert-dismissible fade show">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      {% endfor %}
      {% endif %}

      {% if form.non_field_errors %}
      <div class="alert alert-danger alert-dismissible fade show">
        <b class="text-left">Error:</b> {{ form.non_field_errors | striptags }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      {% endif %}
      {% for field in form %}
      {{ field }}
      {% endfor %}
      <div class="custom-control custom-checkbox mb-3" style="text-align: left;">
        <input type="checkbox" class="custom-control-input" id="customcheck1" value="remember-me"> 
        <label for=customcheck1 class="custom-control-label">Remember me</label>
      </div>
      <button class="btn btn-lg btn-primary btn-block font-weight-bold" type="submit">Sign in</button>
      <hr class="mt-4 mb-2">
    </form>
    </main>
    <footer class="footer">
      <div class="container">
        <span >&copy; 2017-2018</span>
      </div>
    </footer>
  
  </body>
    <script src="{% static 'js/jquery-3.3.1.slim.min.js' %}"></script>
    <script src="{% static 'table-sort/jquery.tablesorter.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</html>

itam/templates/itam/notifications.html
{% extends 'base.html' %}
{% block title %} Notifications {% endblock %}
{% block content %}
  <!-- MAIN SECTION -->
	<main class="main">

		<nav aria-label="breadcrumb">
			<ol class="breadcrumb">
        <li class="breadcrumb-item active"><span>Notifications</span></li>
			</ol>
		</nav>

    <div class="card bg-danger mb-4">
      <div class="card-header text-white">
        <span class="font-weight-bold">Unread Notifications</span>
        {% if unread_notifs %} 
        <form action="{% url 'itam:mark-all-as-read' %}" method="POST" class="d-inline">
          {% csrf_token %}
          <input type="hidden"> 
          <button type="submit" class="btn btn-link btn-sm m-0 p-0 float-right text-white">Mark all as Read</button>
        </form>
        {% endif %}
      </div>
     
      <ul class="list-group list-group-flush">
        {% for a in unread_notifs %}
        <li href=# class="list-group-item list-group-item-action float-left">
          <a href="{{ a.actor.get_absolute_url }}">{{ a.actor }}</a>
          <form action="{% url 'itam:mark-as-read' a.id %}" method=POST class="d-inline">
            {% csrf_token %}
            <input type="hidden" name="a.id" value="{{ a.id }}">
            <button type="submit" class="btn btn-link btn-sm float-right">Mark as Read</button>
          </form>
          {{ a.verb }}
          <footer>{{ a.timestamp }}</footer>
        </li>
        {% endfor %}
      </ul>

    </div> 
    <div class="card bg-success">
      <div class="card-header text-white">
        <span class="font-weight-bold">Read Notifications</span>
        {% if read_notifs %}
        <form action="{% url 'itam:delete-all-notification' %}" method="POST" class="d-inline">
          {% csrf_token %}
          <input type="hidden"> 
          <button type="submit" class="btn btn-link btn-sm m-0 p-0 float-right text-white" 
          onclick="return confirm('Are you sure you want to delete all entries?')">Delete all
          </button>
        </form>
        {% endif %}
      </div>
     
      <ul class="list-group list-group-flush">
        {% for a in read_notifs %}
        <li href=# class="list-group-item list-group-item-action float-left">
          <a href="{{ a.actor.get_absolute_url }}">{{ a.actor }}</a>
          <form action="{% url 'itam:delete-notification' a.id %}" method=POST class="d-inline">
            {% csrf_token %}
            <input type="hidden" name="a.id" value="{{ a.id }}">
            <button type="submit" class="btn btn-link btn-sm float-right mt-1" 
            onclick="return confirm('Are you sure you want to delete this Notification?')">Delete</button>
          </form>
          {{ a.verb }}
          <footer>{{ a.timestamp }}</footer>
        </li>
        {% endfor %}
      </ul>

    </div>

	</main>
{% endblock %}